pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker build --pull --no-cache -t frebib/systemd:$IMAGE $IMAGE/

  test:
    image: tmaier/docker-compose
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      # Fix for running on non-systemd hosts
      - mkdir -p /sys/fs/cgroup/systemd
      - docker-compose up -d $IMAGE
      - sleep 4
      - docker logs $IMAGE
      - docker exec $IMAGE systemctl status
      - docker-compose down

matrix:
  IMAGE:
    - arch
    - debian

# vim: sw=2 et
