services:
  docker:
    image: docker:dind
    privileged: true

pipeline:
  build:
    image: docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker build -t frebib/systemd:$IMAGE $IMAGE/

  test:
    image: tmaier/docker-compose
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - docker-compose up -d $IMAGE
      - sleep 4
      - docker exec $IMAGE systemctl status
      - docker-compose down

matrix:
  IMAGE:
    - arch
    - debian

# vim: sw=2 et
