services:
  docker:
    image: docker:dind
    privileged: true

pipeline:
  build:
    image: docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - apk --no-cache add coreutils
      - find . -wholename '*/Dockerfile' | xargs -n1 dirname | sed 's#^./##g' > builds
      - for n in $(cat builds); do docker build -t frebib/systemd:$n $n/; done

  test:
    image: docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
      - COMPOSE_VERSION=1.14.0
    commands:
      - apk --no-cache add curl
      - curl -OL /usr/local/bin/ https://github.com/docker/compose/releases/download/$COMPOSE_VERSION/docker-compose-`uname -s`-`uname -m`
      - chmod +x /usr/local/bin/docker-compose
      - for n in $(cat builds); do docker-compose up -d $n; sleep 8; docker exec $n systemctl status; done
      - docker-compose down

# vim: sw=2 et
