services:
  docker:
    image: docker:dind
    privileged: true

pipeline:
  build:
    image: docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - apk --no-cache add coreutils
      - find . -wholename '*/Dockerfile' | xargs -n1 dirname | sed 's#^./##g' > builds
      - for n in $(cat builds); do docker build -t frebib/systemd:$n $n/; done

  test:
    image: docker
    environment:
      - DOCKER_HOST=tcp://docker:2375
    commands:
      - for n in $(cat builds); do docker run --name=$n -d frebib/systemd:$n; sleep 5; docker exec $n systemctl status; done
      - docker kill $(docker ps -q)

# vim: sw=2 et
