version: "3.1"

services:
  debian:
    image: frebib/systemd:debian
    restart: always
    build: ./debian
    tty: true
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

  arch:
    image: frebib/systemd:arch
    restart: always
    build: ./arch
    tty: true
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - seccomp:unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

# vim: sw=2
